### ISSUE TITLE
MAPQ zero in unfiltered file

### ISSUE THREAD

**Issue by wkljohn** [walaj/svaba#13]
Are these entries in the unfiltered vcf file with QUAL=LOWMAPQ and one mate with MAPQ=0 means that mate has multiple mapping?

**Comment by walaj** [comment]
It means that one end of the contig has zero mapping quality. This is usually because it has multiple mappings. You can inspect all of the contig alignments (up to 50) in the *.alignments.txt.gz file. In that case, it can't confidently call a rearrangement between A and B since B could be many different locations.
