### ISSUE TITLE
Is it possible to resume a prematurely stopped analysis?

### ISSUE THREAD

**Issue by kgori** [walaj/svaba#37]
Hi Jeremiah

I have an analysis that stopped ~80% of the way through, with a few chromosomes to go. Is there any way to continue the analysis from the point it got up to, and append the results from the last chromosomes to the existing .bps and other output files?

Best,
Kevin.

**Comment by walaj** [comment]
Hi Kevin,

Yes, you can just concatenate the bps.txt.gz files and then run “svaba refilter” to convert the final bps to VCF.

**Comment by kgori** [comment]
Hi Jeremiah,

Thanks for getting back to me so quickly. Could I just check one last thing: should I use the `--region` option to select only the chromosomes the previous run didn't finish? Will it still detect interchromosomal events between the two sets of chromosomes (ones looked at in run 1 and ones looked at in run 2)?

Thanks a lot,
Kevin

**Comment by walaj** [comment]
Hi Kevin,
Correct, although now that I think about it, I think what you'll have to do is give it a BED file of the regions, since there is no way to put in multiple chromosomes as a text input (since it takes samtools view format).

Yes, the interchrom events will be detected as normal, since the regions you set define the anchor window, but of course the partner breakpoint could be anywhere.

I usually just re-run the whole thing to avoid doing the above, if i lose a server or something that stops the run. But the above should work if you're crunched for time.
