### ISSUE TITLE
a question in 'alignment.txt'

### ISSUE THREAD

**Issue by wisekh6** [walaj/svaba#48]
Hi Walaj,

I have a question regarding interpreting the alignment file.
I am looking at one contig's alignment.

The "Global BP" line show presence of a breakpoint between **-** strand on 7:145,643,321 and **+** strand on 7:145,913,731:
`Global BP: : 7:145,643,321(-) to 7:145,913,731(+) SPAN 270410`

However, the corresponding alignment says the breakpoint is between both **+** strands:
![image](https://user-images.githubusercontent.com/3599405/51754082-67777080-2089-11e9-9887-effec6bcb79f.png)

Would you please give me a short description on what those strands mean?

Thank you in advance,

**Comment by walaj** [comment]
The reported "Global BP" is referring to the orientation of the breakpoints, which I define as the direction that a discordant read on that side of the breakpoint would face. For instance, in a deletion:

---A|----DELETED---|B---   

Breakpoint A is + and breakpoint B is - 

On the alignments plot though, I am saying which strand of the reference the contig is aligned to. For instance, in a simple deletion as above, there is no inversion of DNA so the contig will wall be derived from the same strand. 

In an inversion, part of the contig will align to the positive strand, and part to the negative strand. However, the breakpoint orientations will be either ++ or --, since that is the direction that discordant read pairs face for inversions.

Does this help clarify?

**Comment by wisekh6** [comment]
Thanks for your explanation.
