### ISSUE TITLE
Annotate svaba output vcf

### ISSUE THREAD

**Issue by rahulk87** [walaj/svaba#54]
Hi,

Is there a way to annotate svaba output vcf to get gene names and genomic regions etc. I tried snpEFF but it failed to recognize svaba vcf format.

Many thanks,
Rahul

**Comment by walaj** [comment]
Hi Rahul,

I just updated ``R/svaba-annotate.R`` to take a svaba vcf and output gene annotations and fusion-transcript predictions.

Note that you'll need the following packages:
```
plyr
RMySQL
data.table
optparse
roverlaps ## install with devtools::install_github("walaj/roverlaps")
```

**Comment by rahulk87** [comment]
Thanks Jeremiah, this is very helpful. I'll try this and will let you know if I face any issue.

Rahul

**Comment by SilenWang** [comment]
Hi rahulk87
I came across the same problem, and I found it due to the 3 colunms before the actual sample colunm. If you still want to use snpeff, you can manually delete this colunms using `cut` or `awk`, then you can use snpeff to annotate the modified vcf.

**Comment by rahulk87** [comment]
Thanks Silen for telling this. I also tried @walaj method he suggested above, it worked very well too.

**Comment by walaj** [comment]
Thanks Rahul and Silen. You might try using both snpEff and my script, since they do different things. snpEff is great at breakpoint-level annotations, and the annotation script in this repos is more rearrangement-specific and predicts whether a rearrangement creates a putative in-frame sense fusion.
