### ISSUE TITLE
SvABA refilter does not support -Y and -B?

### ISSUE THREAD

**Issue by chunyangbao** [walaj/svaba#55]
Hi,

When I used SvABA refilter, I got the following ERROR message.  It seems that SvABA refilter does not support -Y and -B.  Do you have similar experience?  The FH Version of my SvABA is 134.

$ svaba refilter -i sample.bps.txt.gz \
  -b sample.contigs.bam \
  -a ./refilter/sample \
  -g Homo_sapiens_assembly19.fasta \
  -D data.broadinstitute.org/snowman/dbsnp_indel.vcf \
  -Y data.broadinstitute.org/snowman/viral_database/viral.1.1.genomic_ns.fna \
  -B data.broadinstitute.org/snowman/hg19.svaba.exclude.bed

refilter: invalid option -- 'Y'
refilter: invalid option -- 'B'

Then, I tried install the newest SvABA to fix above issue.  But, I got the following ERROR messages.  Could you please help me to figure out?  Your help is much appreciated!

cram/cram_io.c:57:19: fatal error: bzlib.h: No such file or directory

use .git-2.5.0
use .curl-7.47.1
use .gcc-5.2.0
use .zlib-1.2.8

Thanks,
Chunyang
DFCI

**Comment by walaj** [comment]
Hi Chunyang,

There have been some fixes so I agree it would be good to re-install. It seems you are missing the bzip2 library, so I would try: ``use .bzip2-1.0.6``. Doing a ``use Samtools`` may also do the trick. 

Regarding Y and B for refilter -- since the variants are flagged as either in a blacklist region (B) or as belonging to a microbial genome (Y) during the original run, I don't allow them as parameters in refilter. The idea of refilter is to set a different cutoff for the LOD scores, but changing B or Y would change how the original calls were generated.

However, I see that the help section for ``refilter`` says these are parameters. This is incorrect and I just pushed a change to fix this.

(BTW, I'm thinking I may deprecate "refilter" because the unfiltered VCF already contains all the variants, and so one could filter that using any number of pre-existing VCF parsing / filtering tools (e.g. vcftools). That's probably a better workflow than trying to support my own VCF filtering pipeline.)

Hope that helps,
Jeremiah

**Comment by chunyangbao** [comment]
Very clear.  Thank you!
