### ISSUE TITLE
Fasta output

### ISSUE THREAD

**Issue by ascendo** [walaj/svaba#57]
Jeremiah,
Do you have any plan to add alternative fasta output?
Thanks
-Won

**Comment by walaj** [comment]
Hi Won, could you describe what you mean by that? Do you mean a fasta of assembled contigs?

**Comment by ascendo** [comment]
Yes, after identifying structure variation, can you apply that to reference fasta to generate structure variation applied fasta file?

**Comment by walaj** [comment]
Hi Won,

FYI I added an ``--all-contigs`` option, so that every single assembled contig can be output into the contigs.bam file. You can then just convert the BAM to a fasta if you want to do alignment of the contigs to something else. Just update and rebuild svaba and give it a try. 

Will close for now, but let me know if issues with this.

Best,
Jeremiah
