### ISSUE TITLE
could not find all contigs info

### ISSUE THREAD

**Issue by shishuo16** [walaj/svaba#63]
Hello Jeremiah,
I use the following command to call germline SV, while as the same time ouput all contigs that svaba assembled. 
"svaba run -t ../data/21078731.recal.bam -p 5 -L 6 -I -a germline_run  --germline --all-contigs -G /pnas/pmod/shishuo/ref/hg19/human.fa".
The question is I could not find the output file for all contigs. I have checked "germline_run.contigs.bam" file. But I found that all contigs were mapped to the genome reference. Is that all? What about the contigs that can not map to the reference?
Thanks in advance for you help
Shuo Shi

**Comment by walaj** [comment]
Hi Shuo,
I'm glad you're using the all-contigs options. Indeed, I had a parameter that required a match of greater than 35 bases before the contigs would be output. I believe this is now fixed with the latest commit, so that with the ``--all-contigs`` option, it should output unmatched contigs as well. Give it a try and let me know if issues.
Best,
Jeremiah

**Comment by shishuo16** [comment]
Hi Jeremiah,
Thank you for your work.
When I run command "./configure" to install svaba, I got this errror info "config.status: error: cannot find input file: `SeqLib/src/Makefile.in'"
How so? 
Best,
Shuo

**Comment by walaj** [comment]
Hi Shuo,
I just want to follow up on this. The commit passed all build checks, so it should install just fine. Perhaps just delete and re-clone, to have a fresh directory. 

I'll close for now, but if still having trouble, let me know.
Best,
Jeremiah
