### ISSUE TITLE
Using SVABA to do large scale case/control 

### ISSUE THREAD

**Issue by oalavijeh** [walaj/svaba#75]
Dear team, 

I was looking to compare a cohort of 1000 patients' WGS data against a control population of 30,000 WGS data and was wondering if SVABA would be able to handle these kind of number? This is in a non-cancer population. 

 Would the case/control module be the one to use here?

Many thanks

**Comment by walaj** [comment]
Hi,

What is the depth of sequencing? svaba works better with high-depth since it has to have enough depth of reads to assemble a contig. If the depth is sufficient, you would just run them in small batches (5-10 samples each) just passing each BAM to ``-t``. There would be no control (``-n``) which is fine.

Best,
Jeremiah

**Comment by oalavijeh** [comment]
Hi Jeremiah, 

We have x30 depth. Thanks for the info, I'll have a go. 

All the best

Omid
